language: php
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "vendor"

php:
  - 7.2

dist: xenial

services:
  - mysql

branches:
  only:
    - /^8\.x\-[0-9]+\.x$/

addons:
  artifacts:
    region: eu-west-1
    paths:
      - /tmp/thunder-travis-ci

stages:
  - sanity checks
  - test

jobs:
  include:
    - stage: sanity checks
      name: Verify makefile, check coding standards, check for deprecated code
      before_script: skip
      script:
        - bash -x -e ./scripts/travis/06-test-source-code.sh

    - stage: sanity checks
      name: Check config for composer build
      script:
        - bash -x -e ./scripts/travis/06-run-config-tests.sh

    - stage: sanity checks
      name: Check config for drush_make build
      install:
        - bash -x -e ./scripts/travis/03-download-thunder-drush.sh
      script:
        - bash -x -e ./scripts/travis/06-run-config-tests.sh

    - stage: test
      name: Run tests with composer build

    - stage: test
      name: Run tests with drush_make build
      install:
        - bash -x -e ./scripts/travis/03-download-thunder-drush.sh

    - stage: test
      name: Run update test
      env: TEST_UPDATE=true
      if: commit_message =~ ^\[TEST_UPDATE\] OR type = cron

# The main functionality is divided into different scripts, each is prefixed by a number which
# indicates the execution order
before_install:
  - bash -e ./scripts/travis/00-keep-travis-running.sh &
  - source ./scripts/travis/01-setup-environment.sh
  - bash -x -e ./scripts/travis/02-before-install.sh

install:
  - bash -x -e ./scripts/travis/03-download-thunder-composer.sh

before_script:
  - bash -x -e ./scripts/travis/04-install-thunder.sh
  - bash -x -e ./scripts/travis/05-setup-tests.sh

script:
  - bash -x -e ./scripts/travis/06-run-tests.sh
