language: php
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "vendor"
  - "travis_phantomjs"
php:
#  - 5.6
  - 7.0

env:
#  - INSTALL_METHOD=drush_make
  - INSTALL_METHOD=composer

sudo: false

# match drupal style dev branches and release tags (8.x-1.x or 8.x-1.0)
branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - source ./scripts/travis/setup-environment.sh
  - bash -e ./scripts/travis/before-install.sh

install:
  # Build docroot and install thunder
  - bash -e ./scripts/travis/install.sh

before_script:
  - cd ${TEST_DIR}/docroot
  - drush cr
  - drush runserver --default-server=builtin 8080 &>/dev/null &

script:
  # verify, that makefile is accepted by drupal.org
  - drush verify-makefile
  # Run Drupal tests (@group Thunder)
  - php ${TEST_DIR}/docroot/core/scripts/run-tests.sh --php `which php` --die-on-fail --verbose --url http://localhost:8080 Thunder

  # Run Behat tests
  - behat --config ${THUNDER_DIST_DIR}/tests/behat/behat.travis.yml
