language: php
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "vendor"

php:
  - 7.2

dist: xenial

services:
  - mysql

branches:
  only:
    - /^8\.x\-[0-9]+\.x$/

addons:
  artifacts:
    region: eu-west-1
    paths:
      - /tmp/thunder-travis-ci

stages:
  - sanity checks
  - test

jobs:
  include:
    - stage: sanity checks
      name: Verify makefile, check coding standards, check for deprecated code
      env: INSTALL_METHOD=composer
      install:
        # Install Drush
        - composer global require drush/drush:^8.1
        # Install drupalorg_drush module and verify, that makefile is accepted by drupal.org, otherwise we do not need to go any further
        - drush dl drupalorg_drush-7.x && drush verify-makefile
        - bash -x -e ./scripts/travis/03-download-thunder.sh
      before_script: true
      script:
        - bash -x -e ./scripts/travis/06-test-source-code.sh

    - stage: test
      name: Run tests with composer build
      env: INSTALL_METHOD=composer

    - stage: test
      name: Run tests with drush_make build
      env: INSTALL_METHOD=drush_make
      install:
        # Install Drush
        - composer global require drush/drush:^8.1
        - bash -x -e ./scripts/travis/03-download-thunder.sh

    - stage: test
      name: Run update test
      env: INSTALL_METHOD=composer TEST_UPDATE=true TEST_DEPLOYMENT=true
      if: commit_message =~ ^\[TEST_UPDATE\] OR type = cron
      install:
        # Install Drush
        - composer global require drush/drush:^8.1
        - bash -x -e ./scripts/travis/03-download-thunder.sh

# The main functionality is divided into different scripts, each is prefixed by a number which
# indicates the execution order
before_install:
  - bash -e ./scripts/travis/00-keep-travis-running.sh &
  - source ./scripts/travis/01-setup-environment.sh
  - bash -x -e ./scripts/travis/02-before-install.sh

install:
  - bash -x -e ./scripts/travis/03-download-thunder.sh

before_script:
  - bash -x -e ./scripts/travis/04-install-thunder.sh
  - bash -x -e ./scripts/travis/05-setup-tests.sh

script:
  - bash -x -e ./scripts/travis/06-run-tests.sh
