language: php
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "vendor"
  - "travis_phantomjs"
php:
  - 5.6
  - 7.0

env:
  - INSTALL_METHOD=drush_make
  #- INSTALL_METHOD=composer

sudo: required
dist: trusty

# match drupal style dev branches and release tags (8.x-1.x or 8.x-1.0)
branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - source ./scripts/travis/setup-environment.sh
  - bash -x -e ./scripts/travis/before-install.sh

install:
  - bash -x -e ./scripts/travis/install-requirements.sh
  - bash -x -e ./scripts/travis/install-thunder.sh

before_script:
  - bash -x -e ./scripts/travis/setup-tests.sh

script:
  - bash -x -e ./scripts/travis/run-tests.sh