core.entity_form_display.node.article.default:
  expected_config:
    content:
      field_channel:
        type: options_select
      field_tags:
        settings:
          match_operator: CONTAINS
          placeholder: ''
          size: 60
        third_party_settings: {  }
        type: entity_reference_autocomplete_tags
  update_actions:
    change:
      content:
        field_channel:
          type: select2_autocomplete_widget
        field_tags:
          settings: {  }
          third_party_settings:
            select2boxes:
              enable_preload: false
              preload_count: null
          type: select2_autocomplete_widget
    delete:
      content:
        field_tags:
          settings:
            match_operator: CONTAINS
            placeholder: ''
            size: 60
