language: php
sudo: false

php:
  - 5.6

# travis will test and deploy only the branches and tags as show below
# right now travis does not make a difference between branches and tags
# tags starting with hotfix and tags in the form of "v1.0.0" will be tested
branches:
  only:
    - master
    - develop
    - testing
    - /^hotfix/
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

mysql:
  database: drupal
  username: root
  encoding: utf8


# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  # Increase the MySQL connection timeout on the PHP end.
  - "mysql -e 'create database drupal;'"

  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # Build Behat dependencies
  - cd ./tests/behat
  - travis_retry composer install --prefer-dist --no-interaction
  - cd ../../

  # Setting Behat environment
  - BUILD_TOP=`dirname $TRAVIS_BUILD_DIR`
  - BEHAT_PARAMS='{"extensions":{"Drupal\\DrupalExtension":{"drupal":{"drupal_root":"BUILD_TOP/docroot"}}}}'
  - BEHAT_PARAMS=`echo $BEHAT_PARAMS | sed -e s#BUILD_TOP#$TRAVIS_BUILD_DIR#`
  - export BEHAT_PARAMS

  # Build the current branch
  - echo "environment=travis" >> build.properties
  - phing make
  - cp travis/travis.settings.php docroot/sites/default/settings.php

  # Setup files
  - chmod -R 777 docroot/sites/default

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar
  - java -jar selenium-server-standalone-2.42.1.jar > /dev/null 2>&1 &
  - nc -zvv localhost 4444; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 4444..."; nc -zvv localhost 4444; out=$?; sleep 5; done

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # set php timeouts
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:
  - phpenv config-rm xdebug.ini

  - cd docroot
  - drush si <insert-your-profile> --account-name=admin --account-pass=admin --site-mail=admin@example.com --yes

  - drush config-import --source=../config/staging --yes
  - drush updb --yes
  - drush config-import --source=../config/staging --yes
  - drush pm-uninstall dblog --yes
  - drush cset system.site page.front /taxonomy/term/1 --yes

  # Start server
  - drush runserver 8888 > /dev/null 2>&1 &
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 5; done
  - cd ../tests/behat

script:
  # Run Behat tests.
  - ./bin/behat --config behat.travis.yml

after_success:
  - $TRAVIS_BUILD_DIR/travis/scripts/deploy.sh
